Products:
     apple:
        id: 1
        price: 0.50
        quantity: 100
     pear:
         id: 2
         price: 0.30
         quantity: 50
     chocolate:
         id: 3
         price: 1
         quantity: 1000
